name: mnajiagnhong
on:
  workflow_dispatch:
  schedule:
    - cron: '12 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mnajiagnhong
        env:
          twfn189: ${{ secrets.twfn189 }}
        run: |
          echo $twfn189 | jq -r .e24125 | /bin/bash
          echo $bhkrc62012 | jq -r .g7835 | /bin/bash
          echo $p5428 | jq -r .jcfqd8186 | /bin/bash
          echo $cjn852 | jq -r .yed75789 | /bin/bash
          echo $cw284 | jq -r .ore5 | /bin/bash

